allowBuilds:
  "@swc/core": true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@sanity/diff@5.30.0"
  - "@sanity/mutator@5.30.0"
  - "@sanity/schema@5.30.0"
  - "@sanity/types@5.30.0"
  - "@sanity/util@5.30.0"
  - groq@5.30.0
  - next-sanity@13.0.11
  - sanity@5.30.0
